auto_timeout: false
timeout: 5
max_results: 100
sort_by: 3 # 0 "Resolution", 1 "Seeds", 2 "Size", 3 "Balanced"
use_debug_parser: false
logger_silent: true

# client
public_dns_list: []
opennic_dns_list: []
proxy_enabled: false
proxy_use_type: 0
proxy_host: ""
proxy_port: 8080
proxy_login: ""
proxy_password: ""
proxy_type: 0
use_public_dns: true

kodi_language: false

# <provider>_alias: <provider>
use_0day: false
use_1337x: true
use_3dtrackerru: false
use_baibako: false
use_bithumen: false
use_bitnova: false
use_bluebird: false
use_cpasbien: false
use_ettv: false
use_eztv: false
use_filelist: false
use_filetracker: false
use_gimmepeers: false
use_glotorrents: false
use_hd-torrents: false
use_idope: false
use_ilcorsaroblu: false
use_ilcorsaronero: false
use_ilcorsarored: false
use_iptorrents: false
use_itorrent: false
use_kickass: false
use_kinozal: false
use_limetorrents: false
use_linkomanija: false
use_magnetdl: false
use_megapeer: false
use_mvgroup: false
use_myxzorg: false
use_ncore: false
use_nitro: false
use_nnmclub: false
use_nyaa: false
use_rarbg: true
use_rustorka: false
use_rutor: false
use_rutracker: false
use_serialz: false
use_skytorrents: false
use_sumotorrent: false
use_tfile: false
use_thepiratebay: false
use_toloka: false
use_torlock: false
use_torrent3dru: false
use_torrent9: false
use_torrentdownloads: false
use_torrentfunk: false
use_torrentleech: false
use_torrentlt: false
use_torrentz: false
use_torrentz2k: false
use_uhdbits: false
use_worldwidetorrents: false
use_yggtorrent: false
use_yourbittorrent: false
use_yts: false
use_zamunda: false
use_zelka: false
use_zooqle: false




filter_quotes: true
filter_240p: false
filter_480p: false
filter_720p: true
filter_1080p: true
filter_2k: false
filter_4k: false
filter_music: true
filter_brrip: true
filter_webdl: true
filter_hdrip: true
filter_hdtv: true
filter_dvd: true
filter_dvdscr: false
filter_3d: false
filter_screener: false
filter_telesync: false
filter_cam: false
filter_vhsrip: true
filter_trailer: true
filter_iptvrip: true
filter_workprint: true
filter_line: false
filter_tvrip: false
additional_filters: ""
min_size: 0
max_size: 10000000000
min_size_movies: 0
max_size_movies: 10000000000
min_size_episodes: 0
max_size_episodes: 1000000000
allow_noseeds: false

1337x_contains: 0
eztv_contains: 0
kickass_contains: 0
rarbg_contains: 0
thepiratebay_contains: 0
torrent9_contains: 0
torrentleech_contains: 0

separate_sizes: true
require_resolution: false
require_release_type: false
require_size: false

kickass_alias: false
eztv_alias: false
thepiratebay_alias: false
rarbg_alias: false
eztv_alias: false
1337x_alias: false
kickass_alias: false
torrent9_alias: false
thepiratebay_alias: false
torrentleech_alias: false
1337x_alias: false
rarbg_alias: false
torrent9_alias: false
torrentleech_alias: false